#!/bin/bash
#PBS -P 50000097
#PBS -l walltime=300
#PBS -l select=2:ncpus=112:ngpus=8:mpiprocs=8:mem=1880gb
#PBS -j oe
#PBS -M oculus.quest11@gmail.com
#PBS -m abe
##PBS -l other=hyperthread
#mpirun -hostfile $PBS_NODEFILE -display-map -tag-output -output-filename $HOME/env --map-by ppr:1:node env

module load cuda

time /usr/mpi/gcc/openmpi-4.1.7a1/bin/mpirun \
-hostfile $PBS_NODEFILE \
-map-by ppr:1:node:PE=112 -oversubscribe -use-hwthread-cpus \
-bind-to none --report-bindings -display-map \
-tag-output -output-filename $HOME/run/sglang.$PBS_JOBID \
-x PATH \
-x NCCL_DEBUG=WARN \
-x NCCL_IB_HCA=mlx5_0:1,mlx5_1:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_9:1,mlx5_10:1,mlx5_11:1 \
-x HF_HOME=$HOME/scratch/hf_home \
-x HUGGINGFACE_HUB_CACHE=$HOME/scratch/hf_home/hub \
-x TRANSFORMERS_OFFLINE=1 -x HF_HUB_OFFLINE=1 -x HF_HUB_DISABLE_TELEMETRY=1 \
-x NCCL_NET=IB \
-x NCCL_IB_PCI_RELAXED_ORDERING=1 \
-x DIST_INIT_ADDR=$(head -n 1 $PBS_NODEFILE) \
bash -c 'time $HOME/scratch/py312/bin/python3 -m sglang.bench_offline_throughput \
    --model-path $HOME/scratch/models/DeepSeek-R1 \
    --dataset-path $HOME/scratch/ShareGPT_V3_unfiltered_cleaned_split.json \
    --num-prompts 100 --load-format dummy \
    --enable-dp-attention \
    --tp 16 --dp 2 --nnodes 2 --trust-remote-code \
    --dist-init-addr $DIST_INIT_ADDR:5000 --node-rank $OMPI_COMM_WORLD_RANK'